<header class="HeaderMain" id="header">
    <a class="visuallyhidden" href="#main">Skip to main content</a>
    <div class="HeaderBar">
        <button class="js-hamburger block Button Button--plain NavigationMobileHamburger" type="button" title="Click to open navigation">
            <span class="hamburger">
              <span class="patties"></span>
            </span>
            Menu
        </button>
        <div class="HeaderBar--container">
            <div class="HeaderPageTitle">
                <p>Deakin University Library</p>
            </div>
            <div class="Logo">
                <a class="Logo-link" href="http://www.deakin.edu.au">
                    Deakin University
                </a>
            </div><!-- /.Logo http://www.deakin.edu.au/__data/assets/image/0003/557265/icon_emergency@2x.png http://www.deakin.edu.au/__data/assets/image/0003/557265/icon_emergency@2x.png-->
        </div>
    </div>
    <div class="container Logo">
        <a class="Logo-link" href="/">
            <img src="//www.deakin.edu.au/__data/assets/image/0005/6359/Deakin_Worldly_Logo.png?v=0.5.4" alt="Deakin University Australia" class="logo"/>
        </a>
    </div><!-- /.Logo -->
    <div class="js-navigation-mobile NavigationMobile">
        <div class="block-group">
            <div class="block NavigationMobileSimple">
                <ul class="List List--inline NavigationMobileSimple-list">
                    <li class="List-item">
                        <a href="http://www.deakin.edu.au/locations">Find us</a>
                    </li>
                    <li class="List-item">
                        <a href="http://www.deakin.edu.au/contact-us">Call us</a>
                    </li>
                </ul>
            </div>
            <button class="js-hamburger block Button Button--plain NavigationMobileHamburger" type="button" title="Click to open navigation">
                <i class="fa fa-bars IconFallbackText-icon" aria-hidden="true"></i>
                <span class="IconFallbackText-text">Menu</span>
            </button>
        </div>
    </div><!-- /.NavigationMobile -->

    <div class="js-navigation Navigation">
        <span class="Navigation-heading">Menu</span>
        <button class="js-navigation-close Button Button--plain NavigationClose" type="button" title="Click to close navigation">
            <img alt="Icon close" src="//www.deakin.edu.au/__data/assets/image/0017/325403/icon-close.png?v=0.1.1" width="20">
        </button>
        <nav class="js-navigation-primary NavigationPrimary" role="navigation">
            <div class="clearfix NavigationPrimary-container"></div>
        </nav><!-- /.NavigationPrimary -->

        <div class="NavigationSecondary">
            <div class="clearfix NavigationSecondary-container">
                <ul class="List NavigationSecondary-list">
                    <li class="List-item NavigationSecondary-item">
                        <a class="NavigationSecondary-link NavigationSecondary-link-return" href="http://www.deakin.edu.au">Visit Deakin home
                            <span class="icon-arrow"></span></a>
                    </li>
                </ul>
            </div><!-- /.container -->
        </div>
    </div><!-- /.Navigation -->
</header><!-- /.HeaderMain -->