<div class="span9 first wrap" id="library-search-widget">
    <!-- Search DEV -->
    <div>
        <div id="search-tab" class="tab-pane active">
            <div class="search-tab-content" id="search-tab-content" style="display: block;">
                <div id="content1">
                    <!-- Tab Content -->
                    <div>
                        <form id="ebscohostCustomSearchBox" action="http://encore.deakin.edu.au/iii/encore/Home,$Search.form.sdirect" method="get" class="form-horizontal">
                            <!-- ebsco -->
                            <input class="ebsco" id="ebscohostwindow" name="ebscohostwindow" type="hidden" value="0">
                            <input class="ebsco" id="ebscohosturl" name="ebscohosturl" type="hidden" value="http://search.ebscohost.com/login.aspx?direct=true&amp;site=eds-live&amp;scope=site&amp;type=0&amp;custid=deakin&amp;groupid=main&amp;profid=eds&amp;mode=bool&amp;lang=en&amp;authtype=ip,guest,uid">
                            <input class="ebsco" id="ebscohostsearchsrc" name="ebscohostsearchsrc" type="hidden" value="db">
                            <input class="ebsco" id="ebscohostsearchmode" name="ebscohostsearchmode" type="hidden" value="+">
                            <input class="ebsco" id="ebscohostkeywords" name="ebscohostkeywords" type="hidden" value="">

                            <input type="hidden" name="lib-home" value="1">
                            <div class="lib-search input-append">
                                <label class="visuallyhidden" for="ebscohostsearchtext">Search for books, full text articles and more</label>
                                <input id="ebscohostsearchtext" name="target" type="text" class="large ui-autocomplete-input" placeholder="Search..." data-search="library-search" autocomplete="off">
                                <div class="search-buttons">
                                    <button type="submit" class="btn btn-large btn-primary btn-search" id="btn-library-search"><i class="fa fa-search">&nbsp;</i> Search</button>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div>
                                <ul class="searchnavlinks">
                                    <li class="includepipe"><a id="edsadvancedsearch" href="http://ezproxy.deakin.edu.au/login?url=http://search.ebscohost.com/login.aspx?authtype=ip,guest&custid=deakin&profid=eds&groupid=main&setup=1&direct=true">Advanced Search</a></li>
                                    <li class="includepipe"><a id="catalogue" href="https://encore.deakin.edu.au/iii/encore/?lang=eng">Catalogue</a></li>
                                    <li class="includepipe"><a id="google" href="http://www.deakin.edu.au/library/google-scholar">Google Scholar</a></li>
                                    <li class="includepipe"><a id="databases" href="http://www.deakin.edu.au/library/a-z/databases">A-Z Databases</a></li>
                                    <li><a id="journals" href="http://www.deakin.edu.au/library/a-z/journals">A-Z Journals</a></li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                    <!-- END Tab Content -->
                </div>

            </div>
        </div>
    </div>
</div>